# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{chubasaweber}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["kazuyoshi tlacaelel"]
  s.date = %q{2011-07-20}
  s.description = %q{a chubas aweber}
  s.email = %q{kazu.dev@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc",
     "README.textile"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "lib/chubasaweber.rb",
     "test/helper.rb",
     "test/test_chubasaweber.rb"
  ]
  s.homepage = %q{http://github.com/ktlacaelel/chubasaweber}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A cubas aweber}
  s.test_files = [
    "spec/base_spec.rb",
     "spec/collection_spec.rb",
     "spec/oauth_spec.rb",
     "spec/resource_spec.rb",
     "spec/resources/account_spec.rb",
     "spec/resources/campaign_spec.rb",
     "spec/resources/click_spec.rb",
     "spec/resources/integration_spec.rb",
     "spec/resources/link_spec.rb",
     "spec/resources/list_spec.rb",
     "spec/resources/message_spec.rb",
     "spec/resources/open_spec.rb",
     "spec/resources/subscriber_spec.rb",
     "spec/resources/tracked_event_spec.rb",
     "spec/resources/web_form_spec.rb",
     "spec/resources/web_form_split_test_component_spec.rb",
     "spec/resources/web_form_split_test_spec.rb",
     "spec/spec_helper.rb",
     "test/helper.rb",
     "test/test_chubasaweber.rb",
     "examples/with_access_token.rb",
     "examples/your_account.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

